apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: marscast
  labels:
    app.kubernetes.io/name: marscast
    app.kubernetes.io/component: api
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: marscast
      app.kubernetes.io/component: api
